### Gaussian Naive Bayes

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### EDA

In [5]:
data=pd.read_csv('data/heart (1) (2).csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [7]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [9]:
data.duplicated().sum()

723

In [11]:
data = data.drop_duplicates()

In [13]:
data.duplicated().sum()

0

In [15]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### Splitting X & Y

In [18]:
X=data.drop('target',axis=1)
Y=data['target']

### Scaling

In [24]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
sd=StandardScaler()
X_fit=sd.fit_transform(X)
X_fit

array([[-0.26796589,  0.68265615, -0.93520799, ...,  0.97951442,
         1.27497996,  1.11996657],
       [-0.15726042,  0.68265615, -0.93520799, ..., -2.27118179,
        -0.71491124,  1.11996657],
       [ 1.72473259,  0.68265615, -0.93520799, ..., -2.27118179,
        -0.71491124,  1.11996657],
       ...,
       [-0.26796589,  0.68265615, -0.93520799, ...,  0.97951442,
         0.28003436,  1.11996657],
       [ 0.50697241,  0.68265615,  1.97647049, ...,  0.97951442,
        -0.71491124, -0.51399432],
       [-0.04655495,  0.68265615, -0.93520799, ..., -0.64583368,
         0.28003436,  1.11996657]])

### Splitting into test & train data

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_fit,Y,test_size=0.39,random_state=42)

### Gaussian Naive Bayes

In [54]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)
pred=gb.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Accuracy
from sklearn.metrics import accuracy_score
print(f"accuracy:{accuracy_score(y_test,pred)*100}")

# Classification Report
cr = classification_report(y_test, pred)
print(f"Classification Report:\n{cr}")

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
print(f"Confusion Matrix:\n{cm}")

accuracy:83.05084745762711
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        60
           1       0.81      0.86      0.83        58

    accuracy                           0.83       118
   macro avg       0.83      0.83      0.83       118
weighted avg       0.83      0.83      0.83       118

Confusion Matrix:
[[48 12]
 [ 8 50]]


### KNN

In [38]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

# Accuracy
from sklearn.metrics import accuracy_score
print(f"accuracy {accuracy_score(y_test,y_pred)*100}")

# Classification Report
cr = classification_report(y_test, y_pred)
print(f"Classification Report:\n{cr}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")

accuracy 74.57627118644068
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.67      0.73        60
           1       0.71      0.83      0.76        58

    accuracy                           0.75       118
   macro avg       0.75      0.75      0.74       118
weighted avg       0.75      0.75      0.74       118

Confusion Matrix:
[[40 20]
 [10 48]]


### Logistic regression

In [41]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
y_pred_logreg = logreg.predict(x_test)

# Accuracy
from sklearn.metrics import accuracy_score
print(f"accuracy:{accuracy_score(y_test,y_pred_logreg)*100}")


# Classification Report
cr = classification_report(y_test, y_pred_logreg)
print(f"Classification Report:\n{cr}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_logreg)
print(f"Confusion Matrix:\n{cm}")

accuracy:79.66101694915254
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.77      0.79        60
           1       0.77      0.83      0.80        58

    accuracy                           0.80       118
   macro avg       0.80      0.80      0.80       118
weighted avg       0.80      0.80      0.80       118

Confusion Matrix:
[[46 14]
 [10 48]]


In [62]:
print(f"Gaussian Naive Bayes Accuracy:{accuracy_score(y_test,pred)*100}")
print(f"KNN accuracy {accuracy_score(y_test,y_pred)*100}")
print(f"Logistic Regression accuracy:{accuracy_score(y_test,y_pred_logreg)*100}")


Gaussian Naive Bayes Accuracy:83.05084745762711
KNN accuracy 74.57627118644068
Logistic Regression accuracy:79.66101694915254


In [64]:
#END