### Gaussian Naive Bayes

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### EDA

In [5]:
data=pd.read_csv('data/Bank_Personal_Loan_Modelling.csv')
data.head()

ID_Customer  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0            1   25           1      49     91107       4    1.6          1   
1            2   45          19      34     90089       3    1.5          1   
2            3   39          15      11     94720       1    1.0          1   
3            4   35           9     100     94112       1    2.7          2   
4            5   35           8      45     91330       4    1.0          2   

   Mortgage  Personal Loan  Securities Account  CD Account  Online  CreditCard  
0         0              0                   1           0       0           0  
1         0              0                   1           0       0           0  
2         0              0                   0           0       0           0  
3         0              0                   0           0       0           0  
4         0              0                   0           0       0           1

In [7]:
data.columns

Index(['ID_Customer', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family',
       'CCAvg', 'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [9]:
data.duplicated().sum()

0

In [13]:
data.isna().sum()

ID_Customer           0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [15]:
data.drop(['ID_Customer', 'ZIP Code'], axis=1, inplace=True)

### Splitting X & Y

In [19]:
X = data.drop('Personal Loan', axis=1)
y = data['Personal Loan']

### Scaling

In [21]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
sd=StandardScaler()
X_fit=sd.fit_transform(X)
X_fit

array([[-1.77441684, -1.66607847, -0.53822878, ..., -0.25354028,
        -1.21661774, -0.64531434],
       [-0.02952359, -0.09633022, -0.8641094 , ..., -0.25354028,
        -1.21661774, -0.64531434],
       [-0.55299157, -0.44516316, -1.36379301, ..., -0.25354028,
        -1.21661774, -0.64531434],
       ...,
       [ 1.54088033,  1.64783451, -1.08136314, ..., -0.25354028,
        -1.21661774, -0.64531434],
       [ 1.71536965,  1.73504275, -0.53822878, ..., -0.25354028,
         0.82195086, -0.64531434],
       [-1.51268285, -1.40445376,  0.20043396, ..., -0.25354028,
         0.82195086,  1.54963239]])

### Splitting into test & train data

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_fit, y, test_size=0.3, random_state=42)

### Gaussian Naive Bayes

In [27]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(X_train,y_train)
pred=gb.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Accuracy
from sklearn.metrics import accuracy_score
print(f"accuracy:{accuracy_score(y_test,pred)*100}")

# Classification Report
cr = classification_report(y_test, pred)
print(f"Classification Report:\n{cr}")

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
print(f"Confusion Matrix:\n{cm}")

accuracy:89.2
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1343
           1       0.49      0.60      0.54       157

    accuracy                           0.89      1500
   macro avg       0.72      0.76      0.74      1500
weighted avg       0.90      0.89      0.90      1500

Confusion Matrix:
[[1244   99]
 [  63   94]]


### KNN

In [31]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

# Accuracy
from sklearn.metrics import accuracy_score
print(f"accuracy {accuracy_score(y_test,y_pred)*100}")

# Classification Report
cr = classification_report(y_test, y_pred)
print(f"Classification Report:\n{cr}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")

accuracy 95.86666666666666
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1343
           1       0.93      0.66      0.77       157

    accuracy                           0.96      1500
   macro avg       0.94      0.83      0.87      1500
weighted avg       0.96      0.96      0.96      1500

Confusion Matrix:
[[1335    8]
 [  54  103]]


### Logistic regression

In [35]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)

# Accuracy
from sklearn.metrics import accuracy_score
print(f"accuracy:{accuracy_score(y_test,y_pred_logreg)*100}")


# Classification Report
cr = classification_report(y_test, y_pred_logreg)
print(f"Classification Report:\n{cr}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_logreg)
print(f"Confusion Matrix:\n{cm}")

accuracy:95.19999999999999
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1343
           1       0.85      0.66      0.74       157

    accuracy                           0.95      1500
   macro avg       0.90      0.82      0.86      1500
weighted avg       0.95      0.95      0.95      1500

Confusion Matrix:
[[1324   19]
 [  53  104]]


In [37]:
print(f"Gaussian Naive Bayes Accuracy:{accuracy_score(y_test,pred)*100}")
print(f"KNN accuracy {accuracy_score(y_test,y_pred)*100}")
print(f"Logistic Regression accuracy:{accuracy_score(y_test,y_pred_logreg)*100}")


Gaussian Naive Bayes Accuracy:89.2
KNN accuracy 95.86666666666666
Logistic Regression accuracy:95.19999999999999


In [64]:
#END