### SVM - KNN - Gaussian Naive Bayes

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### EDA

In [3]:
data=pd.read_csv('data/heart.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
data.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [7]:
data.duplicated().sum()

1

In [9]:
data = data.drop_duplicates()

In [11]:
data.duplicated().sum()

0

In [13]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### Splitting X & Y

In [15]:
X = data.drop('target', axis=1)
y = data['target']

### Scaling

In [17]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
sd=StandardScaler()
X_fit=sd.fit_transform(X)
X_fit

array([[ 0.94979429,  0.68265615,  1.97647049, ..., -2.27118179,
        -0.71491124, -2.1479552 ],
       [-1.92854796,  0.68265615,  1.005911  , ..., -2.27118179,
        -0.71491124, -0.51399432],
       [-1.48572607, -1.46486632,  0.0353515 , ...,  0.97951442,
        -0.71491124, -0.51399432],
       ...,
       [ 1.50332164,  0.68265615, -0.93520799, ..., -0.64583368,
         1.27497996,  1.11996657],
       [ 0.28556146,  0.68265615, -0.93520799, ..., -0.64583368,
         0.28003436,  1.11996657],
       [ 0.28556146, -1.46486632,  0.0353515 , ..., -0.64583368,
         0.28003436, -0.51399432]])

### Splitting into test & train data

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_fit,y,test_size=0.39,random_state=42)

In [28]:
from imblearn.over_sampling import SMOTE

if y_train.value_counts().min() < y_train.value_counts().max():
    smote = SMOTE(random_state=42)
    X_train_scaled, y_train = smote.fit_resample(x_train, y_train)
    print("Class distribution after SMOTE:\n", pd.Series(y_train).value_counts())

Class distribution after SMOTE:
 target
1    96
0    96
Name: count, dtype: int64


### SVC - KNN - Gaussian Naive Bayes

In [39]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_model = SVC(kernel='linear', random_state=42)
knn_model = KNeighborsClassifier(n_neighbors=3)
nb_model = GaussianNB()
models = {
    "SVM": svm_model,
    "KNN": knn_model,
    "Naive Bayes": nb_model
}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy * 100:.2f}%")
    print(f"Confusion Matrix for {name}:\n{confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report for {name}:\n{classification_report(y_test, y_pred)}")

SVM Accuracy: 87.29%
Confusion Matrix for SVM:
[[43  7]
 [ 8 60]]
Classification Report for SVM:
              precision    recall  f1-score   support

           0       0.84      0.86      0.85        50
           1       0.90      0.88      0.89        68

    accuracy                           0.87       118
   macro avg       0.87      0.87      0.87       118
weighted avg       0.87      0.87      0.87       118

KNN Accuracy: 82.20%
Confusion Matrix for KNN:
[[42  8]
 [13 55]]
Classification Report for KNN:
              precision    recall  f1-score   support

           0       0.76      0.84      0.80        50
           1       0.87      0.81      0.84        68

    accuracy                           0.82       118
   macro avg       0.82      0.82      0.82       118
weighted avg       0.83      0.82      0.82       118

Naive Bayes Accuracy: 83.90%
Confusion Matrix for Naive Bayes:
[[43  7]
 [12 56]]
Classification Report for Naive Bayes:
              precision    reca

In [27]:
#END