In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

### EDA

In [83]:
df=pd.read_csv('data/hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [84]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()
df['experience']=lr.fit_transform(df['experience'])
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           1                    6.0                           7      60000
3           5                   10.0                          10      65000
4           2                    9.0                           6      70000
5           4                    7.0                          10      62000
6           3                    NaN                           7      72000
7           0                    7.0                           8      80000

In [85]:
df.isna().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [86]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean())

In [87]:
x=df.iloc[:,:-1].values
x

array([[ 6.        ,  8.        ,  9.        ],
       [ 6.        ,  8.        ,  6.        ],
       [ 1.        ,  6.        ,  7.        ],
       [ 5.        , 10.        , 10.        ],
       [ 2.        ,  9.        ,  6.        ],
       [ 4.        ,  7.        , 10.        ],
       [ 3.        ,  7.85714286,  7.        ],
       [ 0.        ,  7.        ,  8.        ]])

In [88]:
y=df.iloc[:,-1]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [89]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[ 1.23959081e+00,  1.22627868e-01,  7.32409613e-01],
       [ 1.23959081e+00,  1.22627868e-01, -1.22068269e+00],
       [-1.12153454e+00, -1.59416228e+00, -5.69651921e-01],
       [ 7.67365737e-01,  1.83941802e+00,  1.38344038e+00],
       [-6.49309470e-01,  9.81022943e-01, -1.22068269e+00],
       [ 2.95140668e-01, -7.35767207e-01,  1.38344038e+00],
       [-1.77084401e-01, -7.62407981e-16, -5.69651921e-01],
       [-1.59375961e+00, -7.35767207e-01,  8.13788459e-02]])

In [90]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)
y_pred

array([86078.09240375, 75519.13285775])

In [91]:
print('coefficient:',lr.coef_)
print('intercept:',lr.intercept_)

from sklearn.metrics import r2_score
print('r2:',r2_score(y_test,y_pred))

coefficient: [-13790.15611325   2497.56939033   2923.05825951]
intercept: 65699.65315768743
r2: -0.3889334596248004


In [92]:
from sklearn.linear_model import Lasso
ls=Lasso(alpha=100)
ls.fit(x_train,y_train)
y_pred=ls.predict(x_test)
print('lasso coefficient:',ls.coef_)

lasso coefficient: [-13530.04106329   2363.13113075   2793.40968559]


In [93]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('mea:',mean_absolute_error(y_test,y_pred))
print('mse:',mean_squared_error(y_test,y_pred))
print('r2:',r2_score(y_test,y_pred))

mea: 10578.777098099083
mse: 135742884.9772547
r2: -0.35742884977254685


In [94]:
from sklearn.linear_model import Ridge
ridge=Ridge(alpha=88)
ridge.fit(x_train,y_train)
y_pred=ridge.predict(x_test)
print('ridge coefficient:',ridge.coef_)

ridge coefficient: [-406.65600161  139.51042265   20.03595638]


In [95]:
print('r2:',r2_score(y_test,y_pred))

r2: -0.7457800438800859


# DecisionTreeRegressor

In [97]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [98]:
test_pred=dt.predict(x_test)
train_pred=dt.predict(x_train)

In [121]:
print('testr2:',r2_score(y_test,test_pred))
print('trainr2:',r2_score(y_train,train_pred))

testr2: -0.040000000000000036
trainr2: 1.0


In [100]:
#END